### PR TITLE
Update librealsense to v2.16.1

### PR DESCRIPTION
**Pull request by DillonSkeehan**
This pulls in librealsense v2.16.1, the most recent librealsense version.  It doesn't touch prebuilt windows libs as I'm not sure we would want to update those if everything is currently working as is.

@jkosmach : please let me know who the most appropriate people are to tag in these PRs.

### CODE REVIEW

**Comment by giadang** [comment]
👍

**Comment by zelonght** [comment]
@willkelleher @DillonSkeehan do we need to merge this or just leave it in update-librealsense-to-v2.16.1 branch?

**Comment by giadang** [comment]
@zelonght I'm working on this branch and test it today before merging. Talked with @willkelleher today

**Comment by zelonght** [comment]
re:"@zelonght I'm working on this branch and test it today before merging. Talked with @willkelleher today" -- noted with thanks!

**Pull request merged**
